language: objective-c

script:
  - xcodebuild test -project AsyncOperation/AsyncOperation.xcodeproj -scheme AsyncOperationTests -sdk iphonesimulator12.2 -destination 'platform=iOS Simulator,name=iPhone 8'
